name: Copy Files from Dantherm Repository

on:
  release:
    types: [published]

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v3

    - name: Clone the Dantherm repository
      run: git clone --depth 1 https://github.com/Tvalley71/dantherm.git

    - name: Copy README.md
      run: cp dantherm/README.md ./README.md

    - name: Remove existing disclaimer from README.md
      run: sed -i '/Disclaimer/,$d' ./README.md

    - name: Append current repository disclaimer
      run: cat ./disclaimer.txt >> ./README.md

    - name: Copy shared code files from the Dantherm integration
      run: |
        cp dantherm/custom_components/dantherm/__init__.py >-
                dantherm/custom_components/dantherm/button.py >-
                dantherm/custom_components/dantherm/config_flow.py >-
                dantherm/custom_components/dantherm/cover.py >-
                dantherm/custom_components/dantherm/device.py >-
                dantherm/custom_components/dantherm/number.py >-
                dantherm/custom_components/dantherm/select.py >-
                dantherm/custom_components/dantherm/sensor.py >-
                dantherm/custom_components/dantherm/switch.py ./custom_components/pluggit/
        cp -r dantherm/custom_components/dantherm/translations ./custom_components/pluggit/translations/

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Copy files from the Dantherm integration during release"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
